name: Linux CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 6 * * 6"
jobs:
  build-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, crystal: latest }
          - { os: ubuntu-latest, crystal: nightly }
    runs-on: ${{matrix.os}}
    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}
      - uses: actions/checkout@v2
      - name: Update system
        run: sudo apt update
      - name: Install dependencies
        run: sudo apt install libgtk-3-dev libwebkit2gtk-4.0-dev
      - name: Install crystal lang dependencies
        run: shards install
      - name: Compile library
        run: make
      - name: Run tests
        run: crystal spec
